name: Push Sagen.Core Package

on: 
  workflow_dispatch
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Create Packages Directory
      run: mkdir src/packages
    - name: Pack
      run: dotnet pack src/Sagen.Core/Sagen.Core.csproj -o src/packages
    - name: Push
      run: dotnet push "src/packages/*.nupkg" --no-build -k ${{ secrets.GITHUBTOKEN }} 
